- name: windows_powershell_update
  src: https://github.com/garethevans-contino/ansible-role-windows-powershell-install.git
  version: master


# collections:
#   # Install a collection from Ansible Galaxy.
#   - name: geerlingguy.php_roles
#     version: 0.9.3
#     source: https://galaxy.ansible.com
