# - name: deekayen.chocolatey
#   src: https://github.com/deekayen/ansible-role-chocolatey.git

- name: windows_common
  src: https://github.com/garethevans-contino/ansible-role-windows-common.git
  version: master

- name: ansible-role-windows-test
  src: https://github.com/garethevans-contino/ansible-role-windows-test.git
  version: master

- name: windows_powershell_update
  src: https://github.com/garethevans-contino/ansible-role-windows-powershell-install.git
  version: master


# collections:
#   # Install a collection from Ansible Galaxy.
#   - name: geerlingguy.php_roles
#     version: 0.9.3
#     source: https://galaxy.ansible.com
