# - hosts: all
#   vars:
#       is_container: false
#
#   roles:
#       - role: "{{ playbook_dir }}"
#         system_is_container: "{{ is_container | default(false) }}"
- import_playbook: playbook.yml
