load "/home/gareth/Code/ge-contino/ansible-playbook-windows-server-pre-2019/kitchen/configure/linux/ansible/provision.rb"
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "alvaro/wouter7"
  c.vm.hostname = "default-ansibleserver.vagrantup.com"
  c.vm.network(:private_network, {:ip=>"172.28.128.10"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-kitchen-default-ansibleserver-c06ff2f2-3e46-4eac-86e1-82bfa91b95d8"
    p.gui = true
    p.linked_clone = true
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
